### ISSUE TITLE
unable to add the element at specific index in dropped items.

### ISSUE THREAD

**Issue by SivaPrakashK90** [ObaidUrRehman/ng-drag-drop#122] opened 2018-04-02 11:46 UTC
Hi,
 I want to add the element to a specific position in the list (i.e. in between element 'A' and 'B' I want to add element 'X'). But in the onDrop event, I'm not getting anything like the index to add the element into specific position at "dropped items" 

can anybody tell me how to add an item to a specific index of dropped items?

**Comment by ObaidUrRehman** [comment] 2018-04-03 13:31
This feature is currently in development. Closing as Duplicate of #12

**Closed by ObaidUrRehman** 2018-04-03 13:31 UTC

**Comment by SivaPrakashK90** [comment] 2018-04-11 11:28
Hi ObaidUrRehman,
Thanks for your updated. I have resolved this issue.

**Steps:**
1. I'm getting closest element where I drop the element.
       var id = element.nativeEvent.target.closest('li').getAttribute('Id');
2.  im find the index of the item in list and pushing item into list from "element.dragData"
       this.ListItems.splice(i, 0, element.dragData);
